SKILL_GRAPH = {
    "variables": [],
    "data_types": ["variables"],
    "conditionals": ["variables"],
    "loops": ["variables"],
    "functions": ["variables", "data_types"],
    "arrays": ["variables", "loops"],
    "strings": ["variables", "arrays"],
    "recursion": ["functions", "conditionals"],
    "sorting": ["arrays", "loops", "time_complexity"],
    "searching": ["arrays", "time_complexity"],
    "oop_classes": ["functions", "data_types"],
    "oop_inheritance": ["oop_classes"],
    "linked_lists": ["pointers", "arrays"],
    "stacks_queues": ["arrays", "functions"],
    "trees": ["recursion", "linked_lists", "pointers"],
    "graphs": ["trees"],
    "dynamic_programming": ["recursion", "arrays", "time_complexity"],
    "greedy": ["sorting", "time_complexity"],
    "time_complexity": ["math_fundamentals"],
    "space_complexity": ["time_complexity"],
    "pointers": ["variables"],
    "hash_tables": ["arrays", "functions"],
    "bit_manipulation": ["math_fundamentals"],
    "math_fundamentals": [],
    "probability": ["math_fundamentals"],
}
